name = "blazenote-backend"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = [ "nodejs_compat" ]

# Custom domain configuration
[[routes]]
pattern = "blazenote-backend.nostalgic-keyframe.sxplab.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "blazenote"
database_id = "a675aaea-daad-4775-ba12-7d4bc6df1072"
migrations_dir = "./migrations"

# [ai]
# binding = "AI"

# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "blazenote"
# preview_bucket_name = "dev-blazenote"

[observability.logs]
enabled = true